ProyectoWeb/urls.py
from django.contrib import admin
from django.urls import path
from AppHealthy.views import *
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", inicio, name="Home"), 
    path("login", inicio_sesion, name="InicioSesion"),
    path("editar/", editarPerfil, name="EditarUser"),
    path("listafrutos/", ListaFrutos.as_view(), name="ListaFrutos"),
    path("listasemillas/", ListaSemillas.as_view(), name="ListaSemillas"),
    path("listaespecias/", ListaEspecias.as_view(), name="ListaEspecias"),
    path("crearfrutos", CrearFrutos.as_view(), name="CrearFrutos"),
    path("crearsemilla", CrearSemillas.as_view(), name="CrearSemillas"),
    path("crearespecias", CrearEspecias.as_view(), name="CrearEspecias"),
    path("actualizafruto/<int:pk>", ActualizaFrutos.as_view(), name="ActualizaFruto"),
    path("actualizasemilla/<int:pk>", ActualizaSemillas.as_view(), name="ActualizaSemilla"),
    path("actualizaespecia/<int:pk>", ActualizaEspecias.as_view(), name="ActualizaEspecia"),
    path("borrarfruto/<int:pk>", BorrarFrutos.as_view(), name="BorrarFruto"),
    path("borrarsemilla/<int:pk>", BorrarSemillas.as_view(), name="BorrarSemilla"),
    path("borrarespecia/<int:pk>", BorrarEspecias.as_view(), name="BorrarEspecia"),
    path("signup/", registro, name="Registrarse"),
    path("logout/", cerrar_sesion, name="CerrarSesion"),
    path("agregar/", agregarAvatar, name="Avatar1"),
    path("aboutme/", acerca, name="Acerca"),
    
    #URL para buscar datos
    path("buscarfrutoseco/", busqueda_frutoseco, name="BuscaFruto"),
    path("buscarsemilla/", busqueda_semilla, name="BuscaSemilla"),
    path("buscarespecia", busqueda_especia, name="BuscaEspecia"),
    path("resultadofrutos/", resultado_buscarfrutoseco),
    path("resultadosemilla/", resultado_buscarsemilla),
    path("resultadoespecias/", resultado_buscarespecia),

    ]   

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AppHealthy/models.py
from django.db import models
from django.contrib.auth.models import User



# Create your models here.

class Frutosecos(models.Model):

    def __str__(self):

        return f"{self.nombre}"
    
    nombre = models.CharField(max_length=40)
    presentacion = models.CharField(max_length=40)
    precio = models.FloatField()

class Semillas(models.Model):

    def __str__(self):

        return f"{self.nombre}"
    
    nombre = models.CharField(max_length=40)
    presentacion = models.CharField(max_length=40)
    precio = models.FloatField()

class Especias(models.Model):

    def __str__(self):

        return f"{self.nombre}"
    
    nombre = models.CharField(max_length=40)
    presentacion = models.CharField(max_length=40)
    precio = models.FloatField()


class Avatar(models.Model):

    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    
    imagen = models.ImageField(upload_to="avatares", null=True, blank=True)

    def __str__(self):
    
        return f"{self.usuario} --- {self.imagen}"

AppHealthy/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from AppHealthy.models import Avatar

class FrutosecoFormulario(forms.Form):
    nombre=forms.CharField()
    presentacion=forms.CharField()
    precio=forms.FloatField()
    
class SemillaFormulario(forms.Form):
    nombre=forms.CharField()
    presentacion=forms.CharField()
    precio=forms.FloatField()

class EspeciaFormulario(forms.Form):
    nombre=forms.CharField()
    presentacion=forms.CharField()
    precio=forms.FloatField()

class RegistrarUsuario(UserCreationForm):
    username = forms.CharField(label="Nombre de usuario")
    email = forms.EmailField(label="Correo Electrónico")
    password1 = forms.CharField(label="Ingrese Password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Reingrese Password", widget=forms.PasswordInput)
    first_name = forms.CharField(label="Ingrese Nombre")
    last_name = forms.CharField(label="Ingrese Apellido")

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2", "first_name", "last_name"]

class EditarUsuario(UserCreationForm):
    email = forms.EmailField(label="Correo Electrónico")
    password1 = forms.CharField(label="Ingrese Password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Reingrese Password", widget=forms.PasswordInput)
    first_name = forms.CharField(label="Ingrese Nombre")
    last_name = forms.CharField(label="Ingrese Apellido")

    class Meta:
        model = User
        fields = ["email", "password1", "password2", "first_name", "last_name"]


class AvatarFormulario(forms.ModelForm):

    class Meta:
        model = Avatar
        fields = [ "imagen"]

AppHealthy/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from AppHealthy.models import Frutosecos, Semillas, Especias
from AppHealthy.forms import *
from AppHealthy.views import *

from django.contrib.auth.models import User
from AppHealthy.models import Avatar


# Create your views here.


def inicio(request):
    
    return render(request, "AppHealthy/inicio.html")

def acerca(request):
    
    return render(request, "AppHealthy/about_me.html")

#vistas de register/login/logout

def inicio_sesion(request):

    if request.method == "POST":

        formulario = AuthenticationForm(request, data = request.POST)

        if formulario.is_valid():
            
            info = formulario.cleaned_data

            usuario = info["username"]
            contra = info["password"]

            usuario_actual = authenticate(username=usuario, password=contra)

            if usuario_actual is not None:
                login(request, usuario_actual)

                return render(request, "AppHealthy/inicio.html", {"mensaje":f"Bienvenido {usuario}"})
            
        else:

            return render(request, "AppHealthy/inicio.html", {"mensaje":f"Error, datos incorrectos"})
    else:

        formulario = AuthenticationForm()

    return render(request, "registro/inicio_sesion.html", {"formu":formulario})

def registro(request):

    if request.method == "POST":
        
        formulario = RegistrarUsuario(request.POST)

        if formulario.is_valid():

            info = formulario.cleaned_data

            usuario = info["first_name"]

            formulario.save()

            return render(request, "AppHealthy/inicio.html", {"mensaje":f"Usuario creado : {usuario}"})
    
    else:

        formulario = RegistrarUsuario()

    return render(request, "registro/registrar_usuario.html", {"formu":formulario})
"""
def editarPerfil(request):
    
    usuario = request.user

    if request.method == "POST":
    
        formulario = EditarUsuario(request.POST)

        if formulario.is_valid():

            info = formulario.cleaned_data

            usuario.email = info["email"]
            usuario.set_password(info["password1"])
            usuario.fist_name =info["first_name"]
            usuario.last_name = info["last_name"]
            usuario.save()
        
            return render(request, "AppHealthy/inicio.html")
        
    else:
        
        formulario = EditarUsuario(initial=
            {"email":usuario.email,
            "first_name":usuario.first_name,
            "last_name":usuario.last_name,})
        
    return render(request, "AppHealthy/editar_usuario.html", {"formu":formulario, "usuario":usuario})
"""

def editarPerfil(request):
    
    usuario_actual = request.user

    if request.method == "POST":
    
        formulario = EditarUsuario(request.POST)

        if formulario.is_valid():

            info = formulario.cleaned_data

            usuario_actual.email = info["email"]
            usuario_actual.first_name = info["first_name"]
            usuario_actual.last_name = info["last_name"]
            
            usuario_actual.set_password(info["password1"])

            usuario_actual.save()

            return render(request, "AppHealthy/inicio.html")
        
    else:
        formulario = EditarUsuario(initial={"first_name":usuario_actual.first_name,
                                            "last_name":usuario_actual.last_name,
                                            "email":usuario_actual.email,})
        
    return render(request, "registro/editar_usuario.html", {"formu":formulario})

def cerrar_sesion(request):
        
    logout(request)

    return render(request, "registro/cerrar_sesion.html")

    
def busqueda_frutoseco(request):

    return render(request, "AppHealthy/busqueda_frutoseco.html")

def resultado_buscarfrutoseco(request):

    if request.method == "GET":

        nombre_buscado = request.GET["buscafruto"]
        
        resultados_frutoseco = Frutosecos.objects.filter(nombre__icontains=nombre_buscado)
    
        return render(request, "AppHealthy/busqueda_frutoseco.html", {"frutos":resultados_frutoseco})

    else:
        return render(request, "AppHealthy/busqueda_frutoseco.html")
    

def busqueda_semilla(request):

    return render(request, "AppHealthy/busqueda_semilla.html")

def resultado_buscarsemilla(request):

    if request.method == "GET":

        nombre_buscado = request.GET["buscasemilla"]
        
        resultados_semillas = Semillas.objects.filter(nombre__icontains=nombre_buscado)
    
        return render(request, "AppHealthy/busqueda_semilla.html", {"semilla": resultados_semillas})

    else:
        return render(request, "AppHealthy/busqueda_semilla.html")

def busqueda_especia(request):

    return render(request, "AppHealthy/busqueda_especias.html")

def resultado_buscarespecia(request):

    if request.method == "GET":

        nombre_buscado = request.GET["buscaespecia"]
        
        resultados_especias = Especias.objects.filter(nombre__icontains=nombre_buscado)
    
        return render(request, "AppHealthy/busqueda_especias.html", {"especia": resultados_especias})

    else:
        return render(request, "AppHealthy/busqueda_especias.html")




#CRUD READ DE PELICULAS --- LISTVIEW --- Vistas basadas en clases

class ListaFrutos(LoginRequiredMixin, ListView):

    model = Frutosecos

class ListaSemillas(LoginRequiredMixin, ListView):

    model = Semillas

class ListaEspecias(LoginRequiredMixin, ListView):

    model = Especias

#CRUD CEATE DE PELICULAS --- CREATEVIEW ---

class CrearFrutos(CreateView):

    model = Frutosecos
    template_name = "AppHealthy/crear_frutos.html"
    fields = {"nombre","presentacion","precio"}
    success_url = "/listafrutos/"

class CrearSemillas(CreateView):

    model = Semillas
    template_name = "AppHealthy/crear_semillas.html"
    fields = {"nombre","presentacion","precio"}
    success_url = "/listasemillas/"

class CrearEspecias(CreateView):

    model = Especias
    template_name = "AppHealthy/crear_especias.html"
    fields = {"nombre","presentacion","precio"}
    success_url = "/listaespecias/"


#CRUD UPDATE DE PELICULAS --- UPDATEVIEW ---

class ActualizaFrutos(UpdateView):

    model = Frutosecos
    template_name = "AppHealthy/crear_frutos.html"
    fields = {"nombre","presentacion","precio"}
    success_url = "/listafrutos/"

class ActualizaSemillas(UpdateView):

    model = Semillas
    template_name = "AppHealthy/crear_semillas.html"
    fields = {"nombre","presentacion","precio"}
    success_url = "/listasemillas/"

class ActualizaEspecias(UpdateView):

    model = Especias
    
    template_name = "AppHealthy/crear_especias.html"
    fields = {"nombre","presentacion","precio"}
    success_url = "/listaespecias/"

#CRUD ELIMINAR PELICULAS --- DELETEVIEW ---

class BorrarFrutos(DeleteView):

    model = Frutosecos
    template_name = "AppHealthy/borrar_fruto.html"
    success_url = "/listafrutos"

class BorrarSemillas(DeleteView):

    model = Semillas
    template_name = "AppHealthy/borrar_semilla.html"
    success_url = "/listasemillas"

class BorrarEspecias(DeleteView):

    model = Especias
    template_name = "AppHealthy/borrar_especia.html"
    success_url = "/listaespecias"

@login_required
def agregarAvatar(request):

    if request.method=="POST":

        form = AvatarFormulario(request.POST, request.FILES)
        
        if form.is_valid():

            usuarioActual = User.objects.get(username=request.user)

            avatar = Avatar(usuario=usuarioActual, imagen=form.cleaned_data["imagen"])

            avatar.save()

            return render(request, "AppHealthy/inicio.html")
    
    else:

        form = AvatarFormulario()
    
    return render(request, "AppHealthy/agregarAvatar.html", {"formulario":form})

AppHealthy/templates/AppHealthy/borrar_especia.html
{% extends "AppHealthy/padre.html" %}

{% block titulo %}
<style>
h4 {color: white}
</style>
<h4> Especias </h4>
&nbsp;

{% endblock %}

{% block contenido1 %}

<form action="" method="POST"> {% csrf_token %}

   <h4> <p> Estás seguro de borrar {{object}} </p> </h4>  

    <input type="submit" value="Borrar">
</form>
{% endblock %}

AppHealthy/templates/AppHealthy/borrar_fruto.html
{% extends "AppHealthy/padre.html" %}

{% block titulo %}
<style>
h4 {color: white}
</style>
<h4> Frutos Secos</h4>
&nbsp;
{% endblock %}

{% block contenido1 %}

<form action="" method="POST"> {% csrf_token %}

   <h4><p> Estás seguro de borrar {{object}} </p> </h4>

    <input type="submit" value="Borrar">
</form>
{% endblock %}

AppHealthy/templates/AppHealthy/borrar_semilla.html
{% extends "AppHealthy/padre.html" %}

{% block titulo %}
<style>
h4 {color: white}
</style>
<h4> Semillas </h4>
&nbsp;

{% endblock %}

{% block contenido1 %}

<form action="" method="POST"> {% csrf_token %}

   <h4> <p> Estás seguro de borrar {{object}} </p> </h4>

    <input type="submit" value="Borrar">
</form>
{% endblock %}

AppHealthy/templates/AppHealthy/busqueda_especias.html
{% extends "AppHealthy/padre.html" %}

{% block titulo %}
<style>
    h4 {color:white}
</style>
    <h4> Buscar especias</h4> 
<br>
<h4>
    <form action="/resultadoespecias/" method="GET"> 

        Nombre : <input type="text" name="buscaespecia">
        
        <input type="submit" value="Buscar"></h4>

    </form>

    {% for x in especia %}
    
    <h4> {{x.nombre}}   {{x.presentacion}}   ${{x.precio}} </h4>
    
    {% endfor %}
    {% endblock %}

AppHealthy/templates/AppHealthy/busqueda_frutoseco.html
{% extends "AppHealthy/padre.html" %}

{% block titulo %}
<style>
    h4 {color:white}
</style>

    <h4> Fruto Seco </h4>
<br>

<h4>
    <form action="/resultadofrutos/" method="GET"> 

        Nombre : <input type="text" name="buscafruto">
        
        <input type="submit" value="Buscar"> </h4>

    </form>

    {% for x in frutos %}

    <h4>{{x.nombre}}   {{x.presentacion}}   ${{x.precio}}</h4>
    
    {% endfor %}
    
    {% endblock %}

AppHealthy/templates/AppHealthy/busqueda_semilla.html
{% extends "AppHealthy/padre.html" %}

{% block titulo %}
<style>
    h4 {color:white}
</style>

    <h4> Buscar semilla </h4>
<br>
<h4>
    
    <form action="/resultadosemilla/" method="GET"> 

        Nombre : <input type="text" name="buscasemilla">
        
        <input type="submit" value="Buscar"> </h4>

    </form>

    {% for x in semilla %}

    <h4> {{x.nombre}}   {{x.presentacion}}   ${{x.precio}} </h4>

    {% endfor %}

    {% endblock %}

AppHealthy/templates/AppHealthy/crear_especias.html
{% extends "AppHealthy/padre.html" %}

{% block titulo %}
<style>
h4 {color: white}
</style>
<h4> Agregar Especias </h4>
<br>
    <form action="" method="POST"> {% csrf_token %}

        <h4>{{form.as_p}}</h4>

        <input type="submit" value="Guardar">
    </form>

{% endblock %}

AppHealthy/templates/AppHealthy/crear_frutos.html
{% extends "AppHealthy/padre.html" %}

{% block titulo %}
<style>
h4 {color: white}
</style>
<h4> Agregar frutos secos</h4>
<br>
    <form action="" method="POST"> {% csrf_token %}

        <h4>{{form.as_p}}</h4>

        <input type="submit" value="Guardar">
    </form>

{% endblock %}

AppHealthy/templates/AppHealthy/crear_semillas.html
{% extends "AppHealthy/padre.html" %}

{% block titulo %}
<style>
h4 {color: white}
</style>
<h4> Agregar Semillas </h4>
<br>
    <form action="" method="POST"> {% csrf_token %}

        <h4>{{form.as_p}}</h4>

        <input type="submit" value="Guardar">
    </form>

{% endblock %}

AppHealthy/templates/AppHealthy/especias_list.html
{% extends "AppHealthy/padre.html" %}

{% block titulo %} 

<form action="/listaespecias/" method="GET"> 
</form>
<style>
    h4 {color:white}
</style>

{% for especia in object_list %}

<h4>
<p> {{especia.nombre}} </p>
</h4>

&nbsp;
<a href="{% url 'ActualizaEspecia' especia.id %}"> Actualizar </a> 
&nbsp;
<a href="{% url 'BorrarEspecia' especia.id %}"> Borar </a>



{% endfor %}
{% endblock %}


{% block contenido1 %}
<br>
<br>
&nbsp;
<a class="btn btn-primary" href="{% url 'CrearEspecias' %}"> Nuevo </a>
&nbsp;
<a class="btn btn-primary" href="{% url 'BuscaEspecia' %}"> Buscar </a>


{% endblock %}

AppHealthy/templates/AppHealthy/frutosecos_list.html
{% extends "AppHealthy/padre.html" %}

{% block titulo %} 

<form action="/listafrutos/" method="GET"> 
</form>
<style>
    h4 {color:white}
</style>

{% for fruto in object_list %}
<br>
<h4>
<p> {{fruto.nombre}} </p>
</h4>

&nbsp;
<a href="{% url 'ActualizaFruto' fruto.id %}"> Actualizar </a> 
&nbsp;
<a href="{% url 'BorrarFruto' fruto.id %}"> Borar </a>



{% endfor %}
{% endblock %}


{% block contenido1 %}
<br>
<br>
&nbsp;
<a class="btn btn-primary" href="{% url 'CrearFrutos' %}"> Nuevo </a>
&nbsp;
<a class="btn btn-primary" href="{% url 'BuscaFruto' %}"> Buscar </a>


{% endblock %}

AppHealthy/templates/AppHealthy/padre.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Proyecto Final Coderr</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'AppHealthy/css/styles.css'%}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
            <div class="container px-1 px-lg-10">
                <a class="navbar-brand" href="{% url 'Home' %}">Home</a>
                <a class="navbar-brand" href="{% url 'Acerca' %}">About me</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                {% if user.is_authenticated %}
                <h6><a class="btn btn-primary" href="{% url 'CerrarSesion' %}">Cerrar Sesión</a></h6>
                &nbsp;
                <h6><a class="btn btn-primary" href="{% url 'EditarUser' %}">Editar Usuario</a></h6>
                &nbsp;
                <img src="{{user.avatar_set.last.imagen.url}}" height="40" width="40">
                &nbsp;
                <h4>Hola {{user.first_name}}</h4>
                {% else %}
                &nbsp;
                <a class="btn btn-primary" href="{% url 'Registrarse' %}">Registrarse</a>
                &nbsp;
                <a class="btn btn-primary" href="{% url 'InicioSesion' %}">Iniciar sesión</a>
                {% endif %}
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item"><a class="nav-link" href="{% url 'ListaFrutos' %}">Frutos Secos</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'ListaSemillas' %}">Semillas</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'ListaEspecias' %}">Especias</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container px-4 px-lg-5 d-flex h-100 align-items-center justify-content-center">
                <div class="d-flex justify-content-center">
                    <div class="text-center">
                        <h1 class="mx-auto my-0 text-uppercase"> {% block titulo %} {% endblock %} </h1>
                        {% block contenido2 %} {% endblock %}
                        {% block contenido1 %} {% endblock %}
                    </div>
                </div>
            </div>
        </header>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

AppHealthy/templates/AppHealthy/semillas_list.html
{% extends "AppHealthy/padre.html" %}

{% block titulo %} 

<form action="/listasemillas/" method="GET"> 
</form>
<style>
    h4 {color:white}
</style>

{% for semilla in object_list %}

<h4>
<p> {{semilla.nombre}} </p>
</h4>

&nbsp;
<a href="{% url 'ActualizaSemilla' semilla.id %}"> Actualizar </a> 
&nbsp;
<a href="{% url 'BorrarSemilla' semilla.id %}"> Borar </a>



{% endfor %}
{% endblock %}


{% block contenido1 %}
<br>
<br>
&nbsp;
<a class="btn btn-primary" href="{% url 'CrearSemillas' %}"> Nuevo </a>
&nbsp;
<a class="btn btn-primary" href="{% url 'BuscaSemilla' %}"> Buscar </a>


{% endblock %}

AppHealthy/templates/AppHealthy/update_especia.html
{% extends "AppHealthy/padre.html" %}

{% block titulo %}
<style>
h4 {color: white}
</style>
<h4> Actualizar especias </h4>
<br>
    <form action="" method="POST"> {% csrf_token %}

        <h4>{{mi_formu.as_p}}</h4>

        <input type="submit" value="Guardar">
    </form>

{% endblock %}